# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created: Thu Aug 28 18:29:41 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(480, 272)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.main_stackedWidget = QtGui.QStackedWidget(MainWindow)
        self.main_stackedWidget.setGeometry(QtCore.QRect(0, 40, 480, 231))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.main_stackedWidget.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        self.main_stackedWidget.setFont(font)
        self.main_stackedWidget.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.main_stackedWidget.setObjectName(_fromUtf8("main_stackedWidget"))
        self.load_percent_scrn = QtGui.QWidget()
        self.load_percent_scrn.setObjectName(_fromUtf8("load_percent_scrn"))
        self.progressBar_percent = QtGui.QProgressBar(self.load_percent_scrn)
        self.progressBar_percent.setGeometry(QtCore.QRect(110, 90, 271, 23))
        self.progressBar_percent.setMaximum(100)
        self.progressBar_percent.setProperty("value", 0)
        self.progressBar_percent.setObjectName(_fromUtf8("progressBar_percent"))
        self.percent_load_lbl = QtGui.QLabel(self.load_percent_scrn)
        self.percent_load_lbl.setGeometry(QtCore.QRect(90, 120, 291, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.percent_load_lbl.setFont(font)
        self.percent_load_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.percent_load_lbl.setObjectName(_fromUtf8("percent_load_lbl"))
        self.main_stackedWidget.addWidget(self.load_percent_scrn)
        self.load_indefinite_scrn = QtGui.QWidget()
        self.load_indefinite_scrn.setObjectName(_fromUtf8("load_indefinite_scrn"))
        self.indefinite_load_lbl = QtGui.QLabel(self.load_indefinite_scrn)
        self.indefinite_load_lbl.setGeometry(QtCore.QRect(90, 120, 291, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.indefinite_load_lbl.setFont(font)
        self.indefinite_load_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.indefinite_load_lbl.setObjectName(_fromUtf8("indefinite_load_lbl"))
        self.progressBar_indefinite = QtGui.QProgressBar(self.load_indefinite_scrn)
        self.progressBar_indefinite.setGeometry(QtCore.QRect(110, 90, 271, 23))
        self.progressBar_indefinite.setMaximum(0)
        self.progressBar_indefinite.setProperty("value", -1)
        self.progressBar_indefinite.setObjectName(_fromUtf8("progressBar_indefinite"))
        self.main_stackedWidget.addWidget(self.load_indefinite_scrn)
        self.choose_ssid_scrn = QtGui.QWidget()
        self.choose_ssid_scrn.setObjectName(_fromUtf8("choose_ssid_scrn"))
        self.wifi_lbl = QtGui.QLabel(self.choose_ssid_scrn)
        self.wifi_lbl.setGeometry(QtCore.QRect(30, 10, 421, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(59, 59, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.wifi_lbl.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.wifi_lbl.setFont(font)
        self.wifi_lbl.setObjectName(_fromUtf8("wifi_lbl"))
        self.wifi_listWidget = QtGui.QListWidget(self.choose_ssid_scrn)
        self.wifi_listWidget.setGeometry(QtCore.QRect(30, 40, 421, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.wifi_listWidget.setFont(font)
        self.wifi_listWidget.setObjectName(_fromUtf8("wifi_listWidget"))
        self.skip_wifi_btn = QtGui.QPushButton(self.choose_ssid_scrn)
        self.skip_wifi_btn.setGeometry(QtCore.QRect(30, 190, 191, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.skip_wifi_btn.setFont(font)
        self.skip_wifi_btn.setObjectName(_fromUtf8("skip_wifi_btn"))
        self.main_stackedWidget.addWidget(self.choose_ssid_scrn)
        self.enter_passkey_scrn = QtGui.QWidget()
        self.enter_passkey_scrn.setObjectName(_fromUtf8("enter_passkey_scrn"))
        self.ssid_lbl = QtGui.QLabel(self.enter_passkey_scrn)
        self.ssid_lbl.setGeometry(QtCore.QRect(10, 10, 121, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.ssid_lbl.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.ssid_lbl.setFont(font)
        self.ssid_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ssid_lbl.setObjectName(_fromUtf8("ssid_lbl"))
        self.ssid_entered_lbl = QtGui.QLabel(self.enter_passkey_scrn)
        self.ssid_entered_lbl.setGeometry(QtCore.QRect(140, 10, 281, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.ssid_entered_lbl.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.ssid_entered_lbl.setFont(font)
        self.ssid_entered_lbl.setText(_fromUtf8(""))
        self.ssid_entered_lbl.setObjectName(_fromUtf8("ssid_entered_lbl"))
        self.password_input = QtGui.QLineEdit(self.enter_passkey_scrn)
        self.password_input.setGeometry(QtCore.QRect(140, 46, 271, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.password_input.setFont(font)
        self.password_input.setText(_fromUtf8(""))
        self.password_input.setObjectName(_fromUtf8("password_input"))
        self.password_lbl = QtGui.QLabel(self.enter_passkey_scrn)
        self.password_lbl.setGeometry(QtCore.QRect(11, 50, 121, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.password_lbl.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.password_lbl.setFont(font)
        self.password_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.password_lbl.setObjectName(_fromUtf8("password_lbl"))
        self.input_help_lbl = QtGui.QLabel(self.enter_passkey_scrn)
        self.input_help_lbl.setGeometry(QtCore.QRect(100, 80, 321, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.input_help_lbl.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.input_help_lbl.setFont(font)
        self.input_help_lbl.setStyleSheet(_fromUtf8("color: #666666;"))
        self.input_help_lbl.setTextFormat(QtCore.Qt.RichText)
        self.input_help_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.input_help_lbl.setObjectName(_fromUtf8("input_help_lbl"))
        self.connecting_lbl = QtGui.QLabel(self.enter_passkey_scrn)
        self.connecting_lbl.setGeometry(QtCore.QRect(60, 140, 351, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.connecting_lbl.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(20)
        self.connecting_lbl.setFont(font)
        self.connecting_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.connecting_lbl.setObjectName(_fromUtf8("connecting_lbl"))
        self.wrong_passwd_lbl = QtGui.QLabel(self.enter_passkey_scrn)
        self.wrong_passwd_lbl.setGeometry(QtCore.QRect(60, 140, 351, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.wrong_passwd_lbl.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(20)
        self.wrong_passwd_lbl.setFont(font)
        self.wrong_passwd_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.wrong_passwd_lbl.setObjectName(_fromUtf8("wrong_passwd_lbl"))
        self.main_stackedWidget.addWidget(self.enter_passkey_scrn)
        self.wifi_connected_scrn = QtGui.QWidget()
        self.wifi_connected_scrn.setObjectName(_fromUtf8("wifi_connected_scrn"))
        self.wifi_connected_lbl = QtGui.QLabel(self.wifi_connected_scrn)
        self.wifi_connected_lbl.setGeometry(QtCore.QRect(40, 70, 401, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(36)
        self.wifi_connected_lbl.setFont(font)
        self.wifi_connected_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.wifi_connected_lbl.setWordWrap(True)
        self.wifi_connected_lbl.setObjectName(_fromUtf8("wifi_connected_lbl"))
        self.main_stackedWidget.addWidget(self.wifi_connected_scrn)
        self.idle_scrn = QtGui.QWidget()
        self.idle_scrn.setObjectName(_fromUtf8("idle_scrn"))
        self.idle_lbl_1 = QtGui.QLabel(self.idle_scrn)
        self.idle_lbl_1.setGeometry(QtCore.QRect(60, 10, 361, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.idle_lbl_1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(32)
        self.idle_lbl_1.setFont(font)
        self.idle_lbl_1.setTextFormat(QtCore.Qt.AutoText)
        self.idle_lbl_1.setAlignment(QtCore.Qt.AlignCenter)
        self.idle_lbl_1.setWordWrap(True)
        self.idle_lbl_1.setObjectName(_fromUtf8("idle_lbl_1"))
        self.idle_lbl_2 = QtGui.QLabel(self.idle_scrn)
        self.idle_lbl_2.setGeometry(QtCore.QRect(60, 70, 361, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.idle_lbl_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.idle_lbl_2.setFont(font)
        self.idle_lbl_2.setTextFormat(QtCore.Qt.AutoText)
        self.idle_lbl_2.setAlignment(QtCore.Qt.AlignCenter)
        self.idle_lbl_2.setWordWrap(True)
        self.idle_lbl_2.setObjectName(_fromUtf8("idle_lbl_2"))
        self.idle_lbl_3 = QtGui.QLabel(self.idle_scrn)
        self.idle_lbl_3.setGeometry(QtCore.QRect(60, 130, 361, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.idle_lbl_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(32)
        self.idle_lbl_3.setFont(font)
        self.idle_lbl_3.setTextFormat(QtCore.Qt.AutoText)
        self.idle_lbl_3.setAlignment(QtCore.Qt.AlignCenter)
        self.idle_lbl_3.setWordWrap(True)
        self.idle_lbl_3.setObjectName(_fromUtf8("idle_lbl_3"))
        self.main_stackedWidget.addWidget(self.idle_scrn)
        self.enter_amount_scrn = QtGui.QWidget()
        self.enter_amount_scrn.setObjectName(_fromUtf8("enter_amount_scrn"))
        self.amount_lbl = QtGui.QLabel(self.enter_amount_scrn)
        self.amount_lbl.setGeometry(QtCore.QRect(100, 20, 321, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.amount_lbl.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(20)
        self.amount_lbl.setFont(font)
        self.amount_lbl.setObjectName(_fromUtf8("amount_lbl"))
        self.amount_input = QtGui.QLineEdit(self.enter_amount_scrn)
        self.amount_input.setGeometry(QtCore.QRect(100, 70, 321, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(26)
        self.amount_input.setFont(font)
        self.amount_input.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.amount_input.setObjectName(_fromUtf8("amount_input"))
        self.currency_lbl = QtGui.QLabel(self.enter_amount_scrn)
        self.currency_lbl.setGeometry(QtCore.QRect(40, 80, 41, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.currency_lbl.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.currency_lbl.setFont(font)
        self.currency_lbl.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.currency_lbl.setObjectName(_fromUtf8("currency_lbl"))
        self.error_text_lbl = QtGui.QLabel(self.enter_amount_scrn)
        self.error_text_lbl.setGeometry(QtCore.QRect(100, 130, 321, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.error_text_lbl.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setItalic(True)
        self.error_text_lbl.setFont(font)
        self.error_text_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.error_text_lbl.setObjectName(_fromUtf8("error_text_lbl"))
        self.main_stackedWidget.addWidget(self.enter_amount_scrn)
        self.pay_loading_scrn = QtGui.QWidget()
        self.pay_loading_scrn.setObjectName(_fromUtf8("pay_loading_scrn"))
        self.pay_loading_lbl = QtGui.QLabel(self.pay_loading_scrn)
        self.pay_loading_lbl.setGeometry(QtCore.QRect(90, 120, 291, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.pay_loading_lbl.setFont(font)
        self.pay_loading_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.pay_loading_lbl.setObjectName(_fromUtf8("pay_loading_lbl"))
        self.pay_loading_progressBar = QtGui.QProgressBar(self.pay_loading_scrn)
        self.pay_loading_progressBar.setGeometry(QtCore.QRect(110, 90, 271, 23))
        self.pay_loading_progressBar.setMaximum(0)
        self.pay_loading_progressBar.setProperty("value", -1)
        self.pay_loading_progressBar.setObjectName(_fromUtf8("pay_loading_progressBar"))
        self.main_stackedWidget.addWidget(self.pay_loading_scrn)
        self.pay_rates_scrn = QtGui.QWidget()
        self.pay_rates_scrn.setObjectName(_fromUtf8("pay_rates_scrn"))
        self.currency_lbl_rates = QtGui.QLabel(self.pay_rates_scrn)
        self.currency_lbl_rates.setGeometry(QtCore.QRect(25, 20, 141, 53))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.currency_lbl_rates.setFont(font)
        self.currency_lbl_rates.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.currency_lbl_rates.setObjectName(_fromUtf8("currency_lbl_rates"))
        self.fiat_amount = QtGui.QLabel(self.pay_rates_scrn)
        self.fiat_amount.setGeometry(QtCore.QRect(170, 30, 191, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(36)
        self.fiat_amount.setFont(font)
        self.fiat_amount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fiat_amount.setObjectName(_fromUtf8("fiat_amount"))
        self.btc_lbl = QtGui.QLabel(self.pay_rates_scrn)
        self.btc_lbl.setGeometry(QtCore.QRect(25, 70, 141, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.btc_lbl.setFont(font)
        self.btc_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.btc_lbl.setObjectName(_fromUtf8("btc_lbl"))
        self.btc_amount = QtGui.QLabel(self.pay_rates_scrn)
        self.btc_amount.setGeometry(QtCore.QRect(170, 80, 191, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(36)
        self.btc_amount.setFont(font)
        self.btc_amount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.btc_amount.setObjectName(_fromUtf8("btc_amount"))
        self.exchange_rate_lbl = QtGui.QLabel(self.pay_rates_scrn)
        self.exchange_rate_lbl.setGeometry(QtCore.QRect(25, 130, 141, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.exchange_rate_lbl.setFont(font)
        self.exchange_rate_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.exchange_rate_lbl.setObjectName(_fromUtf8("exchange_rate_lbl"))
        self.advice_lbl = QtGui.QLabel(self.pay_rates_scrn)
        self.advice_lbl.setGeometry(QtCore.QRect(60, 180, 361, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.advice_lbl.setFont(font)
        self.advice_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.advice_lbl.setObjectName(_fromUtf8("advice_lbl"))
        self.exchange_rate_amount = QtGui.QLabel(self.pay_rates_scrn)
        self.exchange_rate_amount.setGeometry(QtCore.QRect(280, 140, 161, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.exchange_rate_amount.setFont(font)
        self.exchange_rate_amount.setObjectName(_fromUtf8("exchange_rate_amount"))
        self.main_stackedWidget.addWidget(self.pay_rates_scrn)
        self.pay_nfc_scrn = QtGui.QWidget()
        self.pay_nfc_scrn.setObjectName(_fromUtf8("pay_nfc_scrn"))
        self.nfc_advice_lbl = QtGui.QLabel(self.pay_nfc_scrn)
        self.nfc_advice_lbl.setGeometry(QtCore.QRect(210, 0, 261, 201))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.nfc_advice_lbl.setFont(font)
        self.nfc_advice_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.nfc_advice_lbl.setObjectName(_fromUtf8("nfc_advice_lbl"))
        self.show_qr_btn = QtGui.QPushButton(self.pay_nfc_scrn)
        self.show_qr_btn.setGeometry(QtCore.QRect(20, 150, 151, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.show_qr_btn.setFont(font)
        self.show_qr_btn.setObjectName(_fromUtf8("show_qr_btn"))
        self.currency_lbl_nfc = QtGui.QLabel(self.pay_nfc_scrn)
        self.currency_lbl_nfc.setGeometry(QtCore.QRect(15, 40, 41, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.currency_lbl_nfc.setFont(font)
        self.currency_lbl_nfc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.currency_lbl_nfc.setObjectName(_fromUtf8("currency_lbl_nfc"))
        self.fiat_amount_nfc = QtGui.QLabel(self.pay_nfc_scrn)
        self.fiat_amount_nfc.setGeometry(QtCore.QRect(50, 40, 101, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.fiat_amount_nfc.setFont(font)
        self.fiat_amount_nfc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fiat_amount_nfc.setObjectName(_fromUtf8("fiat_amount_nfc"))
        self.btc_amount_nfc = QtGui.QLabel(self.pay_nfc_scrn)
        self.btc_amount_nfc.setGeometry(QtCore.QRect(50, 70, 101, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.btc_amount_nfc.setFont(font)
        self.btc_amount_nfc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.btc_amount_nfc.setObjectName(_fromUtf8("btc_amount_nfc"))
        self.btc_lbl_nfc = QtGui.QLabel(self.pay_nfc_scrn)
        self.btc_lbl_nfc.setGeometry(QtCore.QRect(15, 70, 41, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.btc_lbl_nfc.setFont(font)
        self.btc_lbl_nfc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.btc_lbl_nfc.setObjectName(_fromUtf8("btc_lbl_nfc"))
        self.exchange_rate_nfc = QtGui.QLabel(self.pay_nfc_scrn)
        self.exchange_rate_nfc.setGeometry(QtCore.QRect(50, 100, 101, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.exchange_rate_nfc.setFont(font)
        self.exchange_rate_nfc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.exchange_rate_nfc.setObjectName(_fromUtf8("exchange_rate_nfc"))
        self.exchange_rate_lbl_nfc = QtGui.QLabel(self.pay_nfc_scrn)
        self.exchange_rate_lbl_nfc.setGeometry(QtCore.QRect(15, 100, 41, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.exchange_rate_lbl_nfc.setFont(font)
        self.exchange_rate_lbl_nfc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.exchange_rate_lbl_nfc.setObjectName(_fromUtf8("exchange_rate_lbl_nfc"))
        self.main_stackedWidget.addWidget(self.pay_nfc_scrn)
        self.pay_qr_scrn = QtGui.QWidget()
        self.pay_qr_scrn.setObjectName(_fromUtf8("pay_qr_scrn"))
        self.qr_image = QtGui.QLabel(self.pay_qr_scrn)
        self.qr_image.setGeometry(QtCore.QRect(229, 10, 205, 205))
        self.qr_image.setText(_fromUtf8(""))
        self.qr_image.setScaledContents(True)
        self.qr_image.setObjectName(_fromUtf8("qr_image"))
        self.exchange_rate_qr = QtGui.QLabel(self.pay_qr_scrn)
        self.exchange_rate_qr.setGeometry(QtCore.QRect(50, 100, 101, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.exchange_rate_qr.setFont(font)
        self.exchange_rate_qr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.exchange_rate_qr.setObjectName(_fromUtf8("exchange_rate_qr"))
        self.btc_amount_qr = QtGui.QLabel(self.pay_qr_scrn)
        self.btc_amount_qr.setGeometry(QtCore.QRect(50, 70, 101, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.btc_amount_qr.setFont(font)
        self.btc_amount_qr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.btc_amount_qr.setObjectName(_fromUtf8("btc_amount_qr"))
        self.btc_lbl_qr = QtGui.QLabel(self.pay_qr_scrn)
        self.btc_lbl_qr.setGeometry(QtCore.QRect(15, 70, 41, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.btc_lbl_qr.setFont(font)
        self.btc_lbl_qr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.btc_lbl_qr.setObjectName(_fromUtf8("btc_lbl_qr"))
        self.exchange_rate_lbl_qr = QtGui.QLabel(self.pay_qr_scrn)
        self.exchange_rate_lbl_qr.setGeometry(QtCore.QRect(15, 100, 41, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.exchange_rate_lbl_qr.setFont(font)
        self.exchange_rate_lbl_qr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.exchange_rate_lbl_qr.setObjectName(_fromUtf8("exchange_rate_lbl_qr"))
        self.fiat_amount_qr = QtGui.QLabel(self.pay_qr_scrn)
        self.fiat_amount_qr.setGeometry(QtCore.QRect(50, 40, 101, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.fiat_amount_qr.setFont(font)
        self.fiat_amount_qr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fiat_amount_qr.setObjectName(_fromUtf8("fiat_amount_qr"))
        self.currency_lbl_qr = QtGui.QLabel(self.pay_qr_scrn)
        self.currency_lbl_qr.setGeometry(QtCore.QRect(15, 40, 41, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.currency_lbl_qr.setFont(font)
        self.currency_lbl_qr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.currency_lbl_qr.setObjectName(_fromUtf8("currency_lbl_qr"))
        self.main_stackedWidget.addWidget(self.pay_qr_scrn)
        self.pay_success_scrn = QtGui.QWidget()
        self.pay_success_scrn.setObjectName(_fromUtf8("pay_success_scrn"))
        self.pay_success_lbl = QtGui.QLabel(self.pay_success_scrn)
        self.pay_success_lbl.setGeometry(QtCore.QRect(20, 10, 441, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(28)
        self.pay_success_lbl.setFont(font)
        self.pay_success_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.pay_success_lbl.setObjectName(_fromUtf8("pay_success_lbl"))
        self.touch_for_receipt_lbl = QtGui.QLabel(self.pay_success_scrn)
        self.touch_for_receipt_lbl.setGeometry(QtCore.QRect(230, 100, 211, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.touch_for_receipt_lbl.setFont(font)
        self.touch_for_receipt_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.touch_for_receipt_lbl.setObjectName(_fromUtf8("touch_for_receipt_lbl"))
        self.receipt_qr_image = QtGui.QLabel(self.pay_success_scrn)
        self.receipt_qr_image.setGeometry(QtCore.QRect(40, 80, 135, 135))
        self.receipt_qr_image.setText(_fromUtf8(""))
        self.receipt_qr_image.setScaledContents(True)
        self.receipt_qr_image.setObjectName(_fromUtf8("receipt_qr_image"))
        self.main_stackedWidget.addWidget(self.pay_success_scrn)
        self.pay_cancel_scrn = QtGui.QWidget()
        self.pay_cancel_scrn.setObjectName(_fromUtf8("pay_cancel_scrn"))
        self.pay_cancel_lbl = QtGui.QLabel(self.pay_cancel_scrn)
        self.pay_cancel_lbl.setGeometry(QtCore.QRect(20, 40, 441, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(28)
        self.pay_cancel_lbl.setFont(font)
        self.pay_cancel_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.pay_cancel_lbl.setObjectName(_fromUtf8("pay_cancel_lbl"))
        self.main_stackedWidget.addWidget(self.pay_cancel_scrn)
        self.error_scrn = QtGui.QWidget()
        self.error_scrn.setObjectName(_fromUtf8("error_scrn"))
        self.errors_lbl = QtGui.QLabel(self.error_scrn)
        self.errors_lbl.setGeometry(QtCore.QRect(13, 50, 451, 141))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.errors_lbl.setFont(font)
        self.errors_lbl.setText(_fromUtf8(""))
        self.errors_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.errors_lbl.setWordWrap(True)
        self.errors_lbl.setObjectName(_fromUtf8("errors_lbl"))
        self.main_stackedWidget.addWidget(self.error_scrn)
        self.logo = QtGui.QLabel(MainWindow)
        self.logo.setGeometry(QtCore.QRect(0, 0, 241, 41))
        self.logo.setText(_fromUtf8(""))
        self.logo.setPixmap(QtGui.QPixmap(_fromUtf8("D:/Personal/Google Drive/Work/XBTerminal/designs/logo_device1.png")))
        self.logo.setObjectName(_fromUtf8("logo"))
        self.merchant_name_lbl = QtGui.QLabel(MainWindow)
        self.merchant_name_lbl.setGeometry(QtCore.QRect(240, 0, 231, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setItalic(True)
        self.merchant_name_lbl.setFont(font)
        self.merchant_name_lbl.setText(_fromUtf8(""))
        self.merchant_name_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.merchant_name_lbl.setWordWrap(True)
        self.merchant_name_lbl.setIndent(3)
        self.merchant_name_lbl.setObjectName(_fromUtf8("merchant_name_lbl"))
        self.testnet_notice = QtGui.QLabel(MainWindow)
        self.testnet_notice.setGeometry(QtCore.QRect(140, 0, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.testnet_notice.setFont(font)
        self.testnet_notice.setStyleSheet(_fromUtf8("color: #a61212;"))
        self.testnet_notice.setTextFormat(QtCore.Qt.AutoText)
        self.testnet_notice.setAlignment(QtCore.Qt.AlignCenter)
        self.testnet_notice.setWordWrap(True)
        self.testnet_notice.setIndent(3)
        self.testnet_notice.setObjectName(_fromUtf8("testnet_notice"))

        self.retranslateUi(MainWindow)
        self.main_stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Terminal", None))
        self.percent_load_lbl.setText(_translate("MainWindow", "loading, please wait", None))
        self.indefinite_load_lbl.setText(_translate("MainWindow", "loading, please wait", None))
        self.wifi_lbl.setText(_translate("MainWindow", "please select WiFi network", None))
        self.skip_wifi_btn.setText(_translate("MainWindow", "skip WiFi setup", None))
        self.ssid_lbl.setText(_translate("MainWindow", "selected WiFi", None))
        self.password_lbl.setText(_translate("MainWindow", "password", None))
        self.input_help_lbl.setText(_translate("MainWindow", "2 a b c A B C", None))
        self.connecting_lbl.setText(_translate("MainWindow", "connecting, please wait", None))
        self.wrong_passwd_lbl.setText(_translate("MainWindow", "wrong password", None))
        self.wifi_connected_lbl.setText(_translate("MainWindow", "WiFi connected", None))
        self.idle_lbl_1.setText(_translate("MainWindow", "press", None))
        self.idle_lbl_2.setText(_translate("MainWindow", "any key", None))
        self.idle_lbl_3.setText(_translate("MainWindow", "to begin", None))
        self.amount_lbl.setText(_translate("MainWindow", "amount", None))
        self.currency_lbl.setText(_translate("MainWindow", "£", None))
        self.error_text_lbl.setText(_translate("MainWindow", "no amount entered", None))
        self.pay_loading_lbl.setText(_translate("MainWindow", "preparing payment", None))
        self.currency_lbl_rates.setText(_translate("MainWindow", "£", None))
        self.fiat_amount.setText(_translate("MainWindow", "10.00", None))
        self.btc_lbl.setText(_translate("MainWindow", "m฿", None))
        self.btc_amount.setText(_translate("MainWindow", "12.05", None))
        self.exchange_rate_lbl.setText(_translate("MainWindow", "exchange rate", None))
        self.advice_lbl.setText(_translate("MainWindow", "press enter to accept payment", None))
        self.exchange_rate_amount.setText(_translate("MainWindow", "0.845", None))
        self.nfc_advice_lbl.setText(_translate("MainWindow", "TO PAY\n"
"TOUCH NFC\n"
"NOW", None))
        self.show_qr_btn.setText(_translate("MainWindow", "show QR code", None))
        self.currency_lbl_nfc.setText(_translate("MainWindow", "£", None))
        self.fiat_amount_nfc.setText(_translate("MainWindow", "10.00", None))
        self.btc_amount_nfc.setText(_translate("MainWindow", "12.05", None))
        self.btc_lbl_nfc.setText(_translate("MainWindow", "m฿", None))
        self.exchange_rate_nfc.setText(_translate("MainWindow", "0.845", None))
        self.exchange_rate_lbl_nfc.setText(_translate("MainWindow", "rate", None))
        self.exchange_rate_qr.setText(_translate("MainWindow", "0.845", None))
        self.btc_amount_qr.setText(_translate("MainWindow", "12.05", None))
        self.btc_lbl_qr.setText(_translate("MainWindow", "m฿", None))
        self.exchange_rate_lbl_qr.setText(_translate("MainWindow", "rate", None))
        self.fiat_amount_qr.setText(_translate("MainWindow", "10.00", None))
        self.currency_lbl_qr.setText(_translate("MainWindow", "£", None))
        self.pay_success_lbl.setText(_translate("MainWindow", "payment successful", None))
        self.touch_for_receipt_lbl.setText(_translate("MainWindow", "TOUCH NFC AGAIN\n"
"OR SCAN QR CODE\n"
"FOR RECEIPT", None))
        self.pay_cancel_lbl.setText(_translate("MainWindow", "payment cancelled", None))
        self.testnet_notice.setText(_translate("MainWindow", "testnet\n"
"active", None))

