# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created: Wed Jan  8 13:42:21 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(480, 272)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Form.setPalette(palette)
        self.stackedWidget = QtGui.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 41, 480, 231))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.loading_screen = QtGui.QWidget()
        self.loading_screen.setObjectName(_fromUtf8("loading_screen"))
        self.progressBar = QtGui.QProgressBar(self.loading_screen)
        self.progressBar.setGeometry(QtCore.QRect(170, 110, 148, 23))
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.label_2 = QtGui.QLabel(self.loading_screen)
        self.label_2.setGeometry(QtCore.QRect(170, 60, 211, 41))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.stackedWidget.addWidget(self.loading_screen)
        self.enter_scn = QtGui.QWidget()
        self.enter_scn.setObjectName(_fromUtf8("enter_scn"))
        self.idle_lbl = QtGui.QLabel(self.enter_scn)
        self.idle_lbl.setGeometry(QtCore.QRect(100, 20, 271, 191))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        font.setPointSize(30)
        self.idle_lbl.setFont(font)
        self.idle_lbl.setWordWrap(True)
        self.idle_lbl.setObjectName(_fromUtf8("idle_lbl"))
        self.stackedWidget.addWidget(self.enter_scn)
        self.amount_scn = QtGui.QWidget()
        self.amount_scn.setObjectName(_fromUtf8("amount_scn"))
        self.amount_lbl = QtGui.QLabel(self.amount_scn)
        self.amount_lbl.setGeometry(QtCore.QRect(100, 40, 291, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        font.setPointSize(30)
        self.amount_lbl.setFont(font)
        self.amount_lbl.setObjectName(_fromUtf8("amount_lbl"))
        self.amount_text = QtGui.QLineEdit(self.amount_scn)
        self.amount_text.setGeometry(QtCore.QRect(60, 100, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.amount_text.setFont(font)
        self.amount_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.amount_text.setObjectName(_fromUtf8("amount_text"))
        self.continue_lbl = QtGui.QLabel(self.amount_scn)
        self.continue_lbl.setEnabled(False)
        self.continue_lbl.setGeometry(QtCore.QRect(240, 180, 181, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        self.continue_lbl.setFont(font)
        self.continue_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.continue_lbl.setObjectName(_fromUtf8("continue_lbl"))
        self.currency_lbl = QtGui.QLabel(self.amount_scn)
        self.currency_lbl.setGeometry(QtCore.QRect(30, 100, 31, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.currency_lbl.setFont(font)
        self.currency_lbl.setObjectName(_fromUtf8("currency_lbl"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.amount_scn)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(410, 189, 87, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.next_btn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.next_btn.setObjectName(_fromUtf8("next_btn"))
        self.horizontalLayout.addWidget(self.next_btn)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.amount_scn)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 190, 87, 41))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.cancel_btn = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.cancel_btn.setObjectName(_fromUtf8("cancel_btn"))
        self.horizontalLayout_3.addWidget(self.cancel_btn)
        self.stackedWidget.addWidget(self.amount_scn)
        self.rate_scn = QtGui.QWidget()
        self.rate_scn.setObjectName(_fromUtf8("rate_scn"))
        self.currency_lbl_2 = QtGui.QLabel(self.rate_scn)
        self.currency_lbl_2.setGeometry(QtCore.QRect(10, 20, 31, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.currency_lbl_2.setFont(font)
        self.currency_lbl_2.setObjectName(_fromUtf8("currency_lbl_2"))
        self.fiat_amount = QtGui.QLabel(self.rate_scn)
        self.fiat_amount.setGeometry(QtCore.QRect(50, 30, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.fiat_amount.setFont(font)
        self.fiat_amount.setObjectName(_fromUtf8("fiat_amount"))
        self.btc_lbl = QtGui.QLabel(self.rate_scn)
        self.btc_lbl.setGeometry(QtCore.QRect(10, 60, 31, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.btc_lbl.setFont(font)
        self.btc_lbl.setObjectName(_fromUtf8("btc_lbl"))
        self.btc_amount = QtGui.QLabel(self.rate_scn)
        self.btc_amount.setGeometry(QtCore.QRect(50, 70, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btc_amount.setFont(font)
        self.btc_amount.setObjectName(_fromUtf8("btc_amount"))
        self.exchange_rate_lbl = QtGui.QLabel(self.rate_scn)
        self.exchange_rate_lbl.setGeometry(QtCore.QRect(10, 120, 111, 41))
        self.exchange_rate_lbl.setObjectName(_fromUtf8("exchange_rate_lbl"))
        self.exchange_rate = QtGui.QLabel(self.rate_scn)
        self.exchange_rate.setGeometry(QtCore.QRect(130, 130, 161, 21))
        self.exchange_rate.setObjectName(_fromUtf8("exchange_rate"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.rate_scn)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(350, 190, 178, 41))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.back_btn_2 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.back_btn_2.setObjectName(_fromUtf8("back_btn_2"))
        self.horizontalLayout_2.addWidget(self.back_btn_2)
        self.next_btn_2 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.next_btn_2.setObjectName(_fromUtf8("next_btn_2"))
        self.horizontalLayout_2.addWidget(self.next_btn_2)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.rate_scn)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 190, 87, 41))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.cancel_btn_2 = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.cancel_btn_2.setObjectName(_fromUtf8("cancel_btn_2"))
        self.horizontalLayout_4.addWidget(self.cancel_btn_2)
        self.stackedWidget.addWidget(self.rate_scn)
        self.qr_scn = QtGui.QWidget()
        self.qr_scn.setObjectName(_fromUtf8("qr_scn"))
        self.qr_image = QtGui.QLabel(self.qr_scn)
        self.qr_image.setGeometry(QtCore.QRect(120, 60, 211, 181))
        self.qr_image.setText(_fromUtf8(""))
        self.qr_image.setScaledContents(True)
        self.qr_image.setObjectName(_fromUtf8("qr_image"))
        self.qr_title_lbl = QtGui.QLabel(self.qr_scn)
        self.qr_title_lbl.setGeometry(QtCore.QRect(100, 10, 301, 20))
        self.qr_title_lbl.setObjectName(_fromUtf8("qr_title_lbl"))
        self.qr_address_lbl = QtGui.QLabel(self.qr_scn)
        self.qr_address_lbl.setGeometry(QtCore.QRect(10, 30, 451, 20))
        self.qr_address_lbl.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.qr_address_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.qr_address_lbl.setObjectName(_fromUtf8("qr_address_lbl"))
        self.stackedWidget.addWidget(self.qr_scn)
        self.success_scn = QtGui.QWidget()
        self.success_scn.setObjectName(_fromUtf8("success_scn"))
        self.idle_lbl_2 = QtGui.QLabel(self.success_scn)
        self.idle_lbl_2.setGeometry(QtCore.QRect(100, 10, 271, 191))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        font.setPointSize(30)
        self.idle_lbl_2.setFont(font)
        self.idle_lbl_2.setWordWrap(True)
        self.idle_lbl_2.setObjectName(_fromUtf8("idle_lbl_2"))
        self.stackedWidget.addWidget(self.success_scn)
        self.failed_scn = QtGui.QWidget()
        self.failed_scn.setObjectName(_fromUtf8("failed_scn"))
        self.idle_lbl_3 = QtGui.QLabel(self.failed_scn)
        self.idle_lbl_3.setGeometry(QtCore.QRect(100, 20, 271, 191))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        font.setPointSize(30)
        self.idle_lbl_3.setFont(font)
        self.idle_lbl_3.setWordWrap(True)
        self.idle_lbl_3.setObjectName(_fromUtf8("idle_lbl_3"))
        self.stackedWidget.addWidget(self.failed_scn)
        self.wifi_list_scn = QtGui.QWidget()
        self.wifi_list_scn.setObjectName(_fromUtf8("wifi_list_scn"))
        self.wifi_lbl = QtGui.QLabel(self.wifi_list_scn)
        self.wifi_lbl.setGeometry(QtCore.QRect(30, 10, 151, 21))
        self.wifi_lbl.setObjectName(_fromUtf8("wifi_lbl"))
        self.listWidget = QtGui.QListWidget(self.wifi_list_scn)
        self.listWidget.setGeometry(QtCore.QRect(30, 30, 421, 191))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.stackedWidget.addWidget(self.wifi_list_scn)
        self.wifi_pass_scn = QtGui.QWidget()
        self.wifi_pass_scn.setObjectName(_fromUtf8("wifi_pass_scn"))
        self.ssid_lbl = QtGui.QLabel(self.wifi_pass_scn)
        self.ssid_lbl.setGeometry(QtCore.QRect(20, 50, 41, 31))
        self.ssid_lbl.setObjectName(_fromUtf8("ssid_lbl"))
        self.ssid_entered_lbl = QtGui.QLabel(self.wifi_pass_scn)
        self.ssid_entered_lbl.setGeometry(QtCore.QRect(130, 50, 271, 31))
        self.ssid_entered_lbl.setText(_fromUtf8(""))
        self.ssid_entered_lbl.setObjectName(_fromUtf8("ssid_entered_lbl"))
        self.password_enter = QtGui.QLineEdit(self.wifi_pass_scn)
        self.password_enter.setGeometry(QtCore.QRect(130, 96, 271, 31))
        self.password_enter.setObjectName(_fromUtf8("password_enter"))
        self.password_lbl = QtGui.QLabel(self.wifi_pass_scn)
        self.password_lbl.setGeometry(QtCore.QRect(20, 100, 81, 21))
        self.password_lbl.setObjectName(_fromUtf8("password_lbl"))
        self.label = QtGui.QLabel(self.wifi_pass_scn)
        self.label.setGeometry(QtCore.QRect(30, 160, 421, 61))
        self.label.setObjectName(_fromUtf8("label"))
        self.stackedWidget.addWidget(self.wifi_pass_scn)
        self.wait_scn = QtGui.QWidget()
        self.wait_scn.setObjectName(_fromUtf8("wait_scn"))
        self.wait_lbl = QtGui.QLabel(self.wait_scn)
        self.wait_lbl.setGeometry(QtCore.QRect(190, 70, 181, 31))
        self.wait_lbl.setObjectName(_fromUtf8("wait_lbl"))
        self.progressBar_2 = QtGui.QProgressBar(self.wait_scn)
        self.progressBar_2.setGeometry(QtCore.QRect(170, 110, 131, 23))
        self.progressBar_2.setMaximum(0)
        self.progressBar_2.setProperty("value", -1)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.stackedWidget.addWidget(self.wait_scn)
        self.background = QtGui.QLabel(Form)
        self.background.setGeometry(QtCore.QRect(-10, 0, 501, 41))
        self.background.setStyleSheet(_fromUtf8("QLabel {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(204, 204, 204, 255))\n"
"}"))
        self.background.setText(_fromUtf8(""))
        self.background.setObjectName(_fromUtf8("background"))
        self.logo = QtGui.QLabel(Form)
        self.logo.setGeometry(QtCore.QRect(10, 0, 231, 41))
        self.logo.setText(_fromUtf8(""))
        self.logo.setPixmap(QtGui.QPixmap(_fromUtf8("xbterminal/gui/logo.png")))
        self.logo.setObjectName(_fromUtf8("logo"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label_2.setText(_translate("Form", "Loading Please Wait", None))
        self.idle_lbl.setText(_translate("Form", "<html><head/><body><p align=\"center\">Please press</p><p align=\"center\"><span style=\" font-weight:600;\">ENTER</span></p><p align=\"center\">to begin</p></body></html>", None))
        self.amount_lbl.setText(_translate("Form", "Enter Amount", None))
        self.continue_lbl.setText(_translate("Form", "press enter to continue", None))
        self.currency_lbl.setText(_translate("Form", "£", None))
        self.next_btn.setText(_translate("Form", "Next", None))
        self.cancel_btn.setText(_translate("Form", "Cancel", None))
        self.currency_lbl_2.setText(_translate("Form", "£", None))
        self.fiat_amount.setText(_translate("Form", "0", None))
        self.btc_lbl.setText(_translate("Form", "฿", None))
        self.btc_amount.setText(_translate("Form", "0", None))
        self.exchange_rate_lbl.setText(_translate("Form", "exchange rate", None))
        self.exchange_rate.setText(_translate("Form", "0", None))
        self.back_btn_2.setText(_translate("Form", "Back", None))
        self.next_btn_2.setText(_translate("Form", "Next", None))
        self.cancel_btn_2.setText(_translate("Form", "Cancel", None))
        self.qr_title_lbl.setText(_translate("Form", "Scan QR Code to complete payment", None))
        self.qr_address_lbl.setText(_translate("Form", ".", None))
        self.idle_lbl_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">Payment</p><p align=\"center\">Successful</p></body></html>", None))
        self.idle_lbl_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">Payment</p><p align=\"center\">Failed</p></body></html>", None))
        self.wifi_lbl.setText(_translate("Form", "Wi-Fi", None))
        self.ssid_lbl.setText(_translate("Form", "SSID", None))
        self.password_lbl.setText(_translate("Form", "Password", None))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\">2 a b c A B C</p></body></html>", None))
        self.wait_lbl.setText(_translate("Form", "Please Wait", None))

